### PR TITLE
Install PostgreSQL into `pgsql` conda environment.

### LINKED ISSUE #48: Install PostgreSQL into a separate conda environment.
As the developer, I would like to allow the flexibility to install different versions of PostgreSQL into the same container. In the current approach, we are bound to what is available in the selected Ubuntu release. Things become even more tricky when we want to migrate the database to a newer version of PostgreSQL - it requires both (old and new) versions to be installed in the system at the same time.

Having the PostgreSQL installed in a separated conda environment should allow us both: to install any version of PostgreSQL and as many of those as one desires.

### PR DESCRIPTION
**Pull request by yakutovicha**
fixes #48

### CODE REVIEW

**Review by csadorf — DISMISSED** [review]

**Comment by csadorf** [comment]
@yakutovicha Looks like you need to update the branch?

**Comment by yakutovicha** [comment]
> @yakutovicha Looks like you need to update the branch?

and downgrade PostgreSQL :)

**Comment by csadorf** [comment]
> > @yakutovicha Looks like you need to update the branch?
> 
> and downgrade PostgreSQL :)

Indeed, it is actually not quite clear to me what _exactly_ this PR is trying to achieve. To my understanding it is perfectly fine to use the OS-provided distribution of PGSQL as our main database process, we just need the second installation for the migration. However, this PR seems to generally install PGSQL via conda. Why?

**Comment by yakutovicha** [comment]
> Indeed, it is actually not quite clear to me what _exactly_ this PR is trying to achieve. To my understanding it is perfectly fine to use the OS-provided distribution of PGSQL as our main database process, we just need the second installation for the migration. However, this PR seems to generally install PGSQL via conda. Why?

Well, I wrote the motivation in the issue. The only thing that I could add is that PGSQL=10 is not available in Ubuntu 20/22.

**Comment by csadorf** [comment]
> Well, I wrote the motivation in the issue. The only thing that I could add is that PGSQL=10 is not available in Ubuntu 20/22.

But aren't you replacing the main database installation here which we actually want to be a newer one that is supported by Ubuntu 20/22?

**Comment by yakutovicha** [comment]
> > Well, I wrote the motivation in the issue. The only thing that I could add is that PGSQL=10 is not available in Ubuntu 20/22.
> 
> But aren't you replacing the main database installation here which we actually want to be a newer one that is supported by Ubuntu 20/22?

I would like to downgrade the PGSQL to version 10 because this version is used in all stable AiiDAlab images out there. Once this PR is merged I am going to immediately release a new `aiida-prerequisites` image and make a PR to `aiida-core`. Once a newer version of AiiDA is released, we can base the `aiidalab-docker-stack` on top of it without any problems.

At the same time, I will continue solving the migration issue.

I hope that makes sense

**Comment by csadorf** [comment]
> I hope that makes sense

Unfortunately, not. You say that this effort is part of #44 which is about creating the migration. Why would we need to downgrade for that? We only need a _second_ installation with an older version, no?

Further, you convinced me yesterday that we should press forward with the migration and that trying to get back into a good state on the aiidalab image does not really make sense. Especially since we can always create a new aiidalab image release by simply basing it on an older version of the aiida-core image (e.g. via https://github.com/aiidalab/aiidalab-docker-stack/pull/270).

So we don't need to downgrade the database for the migration nor for creating a new aiidalab release. 😕

**Pull request merged**
