### PR TITLE
Bump conda version: 4.10.3 -> 4.12.0

### PR DESCRIPTION
**Pull request by yakutovicha**

### CODE REVIEW

**Comment by yakutovicha** [comment]
@unkcpz, I have a related question to this PR. Since GitHub actions run on the x86_64 architecture, we do not install conda for the `arm64`. Is that correct?

**Comment by unkcpz** [comment]
> Since GitHub actions run on the x86_64 architecture, we do not install conda for the arm64. Is that correct?

Yes. I think it is related to the discussion here https://github.community/t/ask-about-github-hosted-runners-arm64-platform-support/167483/5. 

The reason I didn't bump the conda version in the arch PR is that I use the Miniconda of python3.9 as default which the python version is `3.9.7`. It will cause issues that python libraries need to be installed with GCC compiler, for example `pip install ruamel.yaml` will fail. Update python version to `3.9.13` fixes it. I think Miniconda with python version `3.8` should be fine but need to test locally.

**Comment by unkcpz** [comment]
Here is a discussion on the feature https://github.com/actions/virtual-environments/issues/2187 
It is on the github roadmap and ETA earliest will be the end of 2022. 🤷🏻‍♂️

**Comment by yakutovicha** [comment]
> Yes. I think it is related to the discussion here https://github.community/t/ask-about-github-hosted-runners-arm64-platform-support/167483/5.

So that means we aren't yet building an `arm64` compatible image, right?

**Comment by yakutovicha** [comment]
> The reason I didn't bump the conda version in the arch PR is that I use the Miniconda of python3.9 as default which the python version is `3.9.7`. It will cause issues that python libraries need to be installed with GCC compiler, for example `pip install ruamel.yaml` will fail. Update python version to `3.9.13` fixes it. I think Miniconda with python version `3.8` should be fine but need to test locally.

So this PR should be fine then, right?

**Comment by unkcpz** [comment]
> So that means we aren't yet building an arm64 compatible image, right?

No, the `buildx` can cross-build image from the other architecture (The images can be found from https://hub.docker.com/r/aiidateam/aiida-prerequisites/tags). It's just not being tested after build (so the `sha256` will be tested but not assured the container can be used for aiidalab image without issue) on GitHub CI.

> So this PR should be fine then, right?

Yes, I approved it.

**Review by unkcpz — APPROVED** [review]
Thanks! Looks all good to me.

**Comment by yakutovicha** [comment]
> No, the `buildx` can cross-build image from the other architecture (The images can be found from https://hub.docker.com/r/aiidateam/aiida-prerequisites/tags).

Right, thanks a lot for the explanation! 👍

**Pull request merged**
