### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by yakutovicha**

### CODE REVIEW

**Review by unkcpz — APPROVED** [review]
@yakutovicha thanks! looks all good.

**Comment by yakutovicha** [comment]
Just to mention that I am waiting for someone (@sphuber or @ltalirz, probably?) to add the right secrets to the repository. I don't have access to the [aiidateambot account](https://hub.docker.com/u/aiidateambot). Without those secrets the image can't be pushed.

**Comment by ltalirz** [comment]
Sorry, I checked and I don't have access to that account.
@sphuber is on holiday at the moment I believe.
Perhaps @giovannipizzi would also have access to the `aiidateambot` dockerhub account?

**Comment by sphuber** [comment]
Should be updated now

**Comment by yakutovicha** [comment]
@sphuber, please make sure to share access to `aiidateambot` with some other members of the team, thanks!

**Comment by sphuber** [comment]
I think both @giovannipizzi and @ramirezfranciscof already have access

**Pull request merged**
